// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Infrastructure.Persistence;

#nullable disable

namespace ProvaPub.Infrastructure.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20260918030102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clayton Will"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Verna Paucek"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ismael Beier"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Karla Bashirian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brooke Langosh"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Maria Watsica"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rudy Ledner"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gabriel Goodwin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kenny Hoppe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jennifer Kreiger"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Perry Prosacco"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gladys Schaefer"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tiffany Prohaska"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Elizabeth Pfannerstill"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Danielle Harris"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Guadalupe Hauck"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Wayne Huels"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Barbara Dach"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Jill Stehr"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Angel Schaefer"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Refined Cotton Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intelligent Wooden Hat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Licensed Granite Gloves"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Licensed Cotton Chips"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ergonomic Concrete Salad"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rustic Concrete Sausages"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sleek Fresh Chicken"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantastic Wooden Bacon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gorgeous Steel Car"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Awesome Granite Salad"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Handcrafted Plastic Salad"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sleek Soft Chair"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sleek Fresh Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Practical Concrete Hat"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Incredible Granite Ball"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sleek Fresh Gloves"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ergonomic Wooden Towels"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rustic Wooden Pizza"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Tasty Rubber Gloves"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Domain.Order", b =>
                {
                    b.HasOne("ProvaPub.Domain.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Domain.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
